### ISSUE TITLE
Can't roundtrip ufo to glyphs

### ISSUE THREAD

**Issue by m4rc1e** [TypeNetwork/josefinsans#9]
When I run ufo2glyphs on the ufos in ufo-fea-conv-2, I get the following traceback:

```
Traceback (most recent call last):
  File "/Users/marcfoley/Type/glyphsLib/venv/bin/ufo2glyphs", line 11, in <module>
    load_entry_point('glyphsLib', 'console_scripts', 'ufo2glyphs')()
  File "/Users/marcfoley/Type/glyphsLib/Lib/glyphsLib/cli.py", line 269, in _ufo2glyphs_entry_point
    return main(args)
  File "/Users/marcfoley/Type/glyphsLib/Lib/glyphsLib/cli.py", line 170, in main
    return options.func(options)
  File "/Users/marcfoley/Type/glyphsLib/Lib/glyphsLib/cli.py", line 245, in ufo2glyphs
    object_to_read, minimize_ufo_diffs=options.no_preserve_glyphsapp_metadata
  File "/Users/marcfoley/Type/glyphsLib/Lib/glyphsLib/builder/__init__.py", line 139, in to_glyphs
    return builder.font
  File "/Users/marcfoley/Type/glyphsLib/Lib/glyphsLib/builder/builders.py", line 653, in font
    self.to_glyphs_glyph(glyph, layer, master)
  File "/Users/marcfoley/Type/glyphsLib/Lib/glyphsLib/builder/glyph.py", line 237, in to_glyphs_glyph
    self.to_glyphs_hints(ufo_glyph, layer)
  File "/Users/marcfoley/Type/glyphsLib/Lib/glyphsLib/builder/hints.py", line 59, in to_glyphs_hints
    value = Point(*hint[attr])
TypeError: __init__() takes from 1 to 4 positional arguments but 5 were given
```

When you converted the glyphs file to a ufo, the glyphs file contained hints. GlyphsLib cannot convert hints from glyphs files into ufos well. It currently doesn't [support up/down hints](https://github.com/googlefonts/glyphsLib/blob/master/Lib/glyphsLib/builder/hints.py#L52) which these ufos have.

I recommend you strip out all the hinting from each glyph. Running `grep "hint" "."` on the ufo dir reveals the hints are stored as `<key>com.schriftgestaltung.hints</key>`

cc @davelab6

**Comment by djrrb** [comment]
@m4rc1e alright I think I’ve removed all instances of `com.schriftgestaltung.hints` from the font and glyph libs, and rebuilt the files. Can you tell me if this helps the situation at all?

**Comment by m4rc1e** [comment]
Rollback to ufos now work in branch `fea-ufo-conv-2`
